### ISSUE TITLE
MusicFestival template with Nuxt js 

### ISSUE THREAD

**Issue by sreddim** [episerver/musicfestival-vue-template#12]
Hi, Can we use this with Vue and Nuxt Js? Can you provide any insight how we can do that with a sample routing configuration?

**Comment by seriema** [comment]
Hi @sreddim 
I'm not familiar with Nuxt JS, but from the introduction of it seems to abstracting away server and client-side rendering. We haven't worked on server-side rendering yet. You can follow issue #7 for that. If you do find a way that works for you, please share it.
